### ISSUE TITLE
[TASK] Add environments for deployment

### ISSUE THREAD

**Issue by lbk003** [KhalisFoundation/gurmukhi#13]
## Summary
Add environments for deployment.

## Description
All secrets, API keys, env variables should pick up the correct value depending on the environment built and deployed to in the github actions. 

This is a very high level description of the task. Please create smaller tasks as needed.

See https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment

**Comment by MySmilingTurban** [comment]
Done ✅
